version: '2'
services:
 node:
  image: madhu25/node2
  ports:
  - "9080:3010"
 # environment:
  # url_name: "172.27.59.67:27017"
  links:
   - mongodb
 mongodb:
  image: madhu25/ankitkmongo1
  ports:
  - "27017:27017"
